all done
OlenaTsapliuk/nodejs-homework-rest-api pull request #3
Opened 2021-11-05 15:44 UTC by OlenaTsapliuk

2021-11-05 22:44 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://ElenaAdmin:6121989enm@cluster0.tcqs3.mongodb.net/Simple-restAPI?retryWrites=true&w=majority
плохая практика - креды к базам данных пушить в гит нельзя

2021-11-05 23:04 UTC, KirillKulakow commented on model/contact.js
> +  { versionKey: false, timestamps: true }
проверь у себя локально - работает ли у тебя данное приложение при взаимодействии с базой, как по мне ты пропустила поле названия коллекции в которой хранятся контакты

2021-11-05 23:08 UTC, KirillKulakow commented on package.json
> +    "mongodb": "^4.1.3",
зачем тебе это?

2021-11-05 23:08 UTC, KirillKulakow requested changes
Need fix

2021-11-06 09:27 UTC, OlenaTsapliuk commented on .env
> +DB_HOST=mongodb+srv://ElenaAdmin:6121989enm@cluster0.tcqs3.mongodb.net/Simple-restAPI?retryWrites=true&w=majority
Добавила в gitignore, забыла в прошлый раз

2021-11-06 09:29 UTC, OlenaTsapliuk commented on model/contact.js
> +  { versionKey: false, timestamps: true }
В се работает отлично, через postman все добавляет, обновляет и удаляет с базы, через Compass захожу вижу все изменения

2021-11-06 09:36 UTC, OlenaTsapliuk commented on package.json
> +    "mongodb": "^4.1.3",
я пробовала работать по конспекту, сделала uninstall

2021-11-06 10:04 UTC, KirillKulakow approved these changes

2021-11-08 17:17 UTC, merged