all
OlenaTsapliuk/nodejs-homework-rest-api pull request #4
Opened 2021-11-12 15:43 UTC by OlenaTsapliuk

2021-11-13 11:20 UTC, KirillKulakow commented on .env
удали этот файл из репозитория!!! вместо него оставь только .env.example

2021-11-13 11:22 UTC, KirillKulakow commented on controllers/auth/login.js
> +  // if(!user){
удалить или использовать

2021-11-13 11:22 UTC, KirillKulakow commented on controllers/auth/register.js
> +// const bcrypt = require("bcryptjs");
удалить

2021-11-13 11:22 UTC, KirillKulakow commented on controllers/auth/register.js
> +  res.status(201).json({
удалить

2021-11-13 11:23 UTC, KirillKulakow commented on controllers/auth/register.js
> +  //   const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10));
удалить

2021-11-13 11:28 UTC, KirillKulakow commented on middlewares/validation.js
> +const validation = (schema) => {
можно упростить через замыкания (schema) => (req, res, next) => {}
и я никак не могу понять зачем вы ставите нижнее подчеркивание? в чем смысл? а если захотите юзать lodash?

2021-11-13 11:28 UTC, KirillKulakow commented on middlewares/controllerWrapper.js
> +const controllerWrapper = (ctrl) => {
так же можно использовать замыкания

2021-11-13 11:30 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если я как не авторизированный пользователь захочу посмотреть список контактов то получу ошибку 500 - не хорошо (ошибка в данной строке)

2021-11-13 11:34 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const skip = (page - 1) * limit;
незнаю как у других, но у нас не любят не обоснованных констант (1) - рекомендую написать например так: page * limit - limit

2021-11-13 11:36 UTC, KirillKulakow commented on controllers/auth/login.js
> +// const bcrypt = require("bcryptjs");
удалить

2021-11-13 11:37 UTC, KirillKulakow commented on controllers/auth/currentUser.js
> +  const user = await User.findById(_id, "email subscription");
у тебя вся информация по юзеру хранится в req.user, так зачем делать лишний запрос?

2021-11-13 11:38 UTC, KirillKulakow requested changes
need fix

2021-11-15 08:29 UTC, OlenaTsapliuk commented on .env
У меня добавлен он в гитигнор еще из прошлого раза( незнаю почему он подтягивает(

2021-11-15 08:30 UTC, OlenaTsapliuk commented on controllers/auth/login.js
> +  // if(!user){
Закоментированый код оставлять никак нельзя? я оставляю лично для себя...

2021-11-15 08:31 UTC, OlenaTsapliuk commented on controllers/auth/login.js
> +  // if(!user){
Удалила

2021-11-15 10:56 UTC, OlenaTsapliuk commented on .env
я удалила у всех ветках его

2021-11-15 20:07 UTC, KirillKulakow commented on controllers/auth/currentUser.js
> +  if (!req.user) {
лишняя проверка - так как ты в middleware проводишь аутентификацию

2021-11-15 20:15 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const { _id } = req.user;
сделай тут еще проверку на число, если page или limit это не число выдать badrequest

2021-11-15 20:16 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const skip = page * limit - limit;
и лучше перед этим просчетом преобразовать строки в числа

2021-11-15 20:16 UTC, KirillKulakow requested changes
Need fix

2021-11-15 21:58 UTC, OlenaTsapliuk commented on controllers/auth/currentUser.js
> +  if (!req.user) {
убрала

2021-11-16 20:03 UTC, KirillKulakow approved these changes

2021-11-16 20:05 UTC, merged