error
OlenaTsapliuk/nodejs-homework-rest-api pull request #5
Opened 2021-11-19 10:57 UTC by OlenaTsapliuk

2021-11-20 11:42 UTC, KirillKulakow commented on controllers/auth/register.js
> +  const avatarURL = gravatar.url(email);
здесь возвратится не корректная ссылка на аватарку - без протокола

2021-11-20 11:45 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +  if (!req.user) {
лишняя проверка

2021-11-20 11:47 UTC, KirillKulakow requested changes
Need fix

2021-11-20 20:09 UTC, OlenaTsapliuk commented on controllers/auth/register.js
> +  const avatarURL = gravatar.url(email);
добавила {protocol:'http'}

2021-11-20 20:10 UTC, OlenaTsapliuk commented on controllers/auth/updateAvatar.js
> +  if (!req.user) {
убрала проверку, добавила проверку на Mime type

2021-11-20 20:41 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +    const avatar = path.join("/avatars", filename);
вот здесь было бы хорошо добавить hostname - чтобы путь отображался так: "http://localhost:3000/avatars/..."

2021-11-20 20:42 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +    const avatar = path.join("/avatars", filename);
или можно оставить так как есть но там где отдается путь к аватарке отдавать с hostname

2021-11-20 20:43 UTC, KirillKulakow requested changes
One comment

2021-11-21 10:12 UTC, KirillKulakow approved these changes

2021-11-21 10:12 UTC, merged