verify
OlenaTsapliuk/nodejs-homework-rest-api pull request #6
Opened 2021-11-25 08:21 UTC by OlenaTsapliuk

2021-11-25 21:02 UTC, KirillKulakow commented on controllers/auth/login.js
> +  if (!user || !user.verify || !user.comparePassword(password)) {
лучше сделать отдельную ошибку для user.verify

2021-11-25 21:05 UTC, KirillKulakow commented on controllers/auth/verify.js
> +  const user = await User.findOne({ verificationToken });
можно сразу выполнить команду findOneAndUpdate и если ничего не вернется вернуть ошибку
только нужно поставить опцию возврата обновленного документа

2021-11-25 21:06 UTC, KirillKulakow requested changes
Need some fix

2021-11-26 10:35 UTC, OlenaTsapliuk commented on controllers/auth/login.js
> +  if (!user || !user.verify || !user.comparePassword(password)) {
сделала

2021-11-26 19:57 UTC, KirillKulakow approved these changes

2021-11-27 19:01 UTC, merged